### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AntVadala** [t-babin/ACC-Telemetry-Tracker#1]
Hey, I want to use your work but the installation process is not very detailed. Do you mind me asking if you have more detailed instructions?.

**Comment by t-babin** [comment]
I've just updated the documentation, hopefully that helps.

**Comment by AntVadala** [comment]
Hey, after months I returned to this app but every time after trying to loggin in It returns to the "unauthenticated page", even after correcting the oauth link to discord. Maybe it's just that it's not on my network and therefore every refer to localhost doesn't work. After changing tho nothing changed (connection refused to](https://[localhost](http://***.***.*.***/):7112/api/auth/callback?code=D4X0KJQy0Szb9dJWhnz6ROwbJKOtJE net::ERR_CONNECTION_REFUSED). I checked all your code and apart from the url I didn't saw anything wrong. Thanks in advance

**Comment by t-babin** [comment]
One thing I forget to mention in the instructions (will be updated) is that your discord application needs to have <frontend-url>/auth as a redirect URI (i.e. http://localhost:4200/auth). Double check that all of your configuration values are correct. If you're running via docker also make sure that you have no values in the `client/acc-telemetry-tracker/src/assets/env.js` file since those values will be populated by the docker environment variables.

**Comment by AntVadala** [comment]
I tried all of the above and nothing, same thing. Connection refused to « (https://[localhost](http://%2A%2A%2A.%2A%2A%2A.%2A.%2A%2A%2A/):7112/api/auth/callback?code=D4X0KJQy0Szb9dJWhnz6ROwbJKOtJE ». Indeed if I disable the requirement to be apart of a guild the error "Sorry, you are not a member of the discord server"persist". Even locally if I try to get something from the port 7112 I get connection refused.
![Screenshot 2022-07-11 134702](https://user-images.githubusercontent.com/99339917/178257460-c7905f6c-c36b-4a7c-9743-42afc77d883a.png)

**Comment by t-babin** [comment]
Is the backend running? That page is displayed whenever there is an error when logging in - it isn't actually checking your guild membership yet. Potentially you have a firewall blocking traffic on that port.

**Comment by AntVadala** [comment]
Apparently docker doesn't run the backend, the problem is there I think. I tried to run docker and at the same time the backend and now any error show up but the "Sorry, you are not a member of the discord server" is still there. At this point I don't have any ideas

**Comment by t-babin** [comment]
Are you running with the sample docker compose I provided or just the dockerfiles directly? Either way, the backend container should log to both the docker console as well as to a file if you mounted a volume to the logs directory. Those logs should hopefully give a clue as to what is happening and why it isn't working. If you're being redirected to the unauthorized page it's because the backend auth api is returning an error. This could be because it isn't running, the discord authentication is failing (the response from discord is logged), or the user isn't in the provided discord guild (which can be disabled).

**Comment by AntVadala** [comment]
After trying for days now I receive no errors, but the problem's still there. I think that maybe is the authentication to discord. Perhaps I changed some raws on the authentication file for the redirection to work.

FROM
authorize(): void {
        const url =
            'https://discord.com/api/oauth2/authorize?'
            + 'response_type=code'
            + `&client_id=${this.DISCORD_CLIENT_ID}`
            + `&redirect_uri=${window.location.origin}/auth`
            + '&scope=identify guilds guilds.members.read';

TO

authorize(): void {
        const url =
            'https://discord.com/api/oauth2/authorize?'
            + `client_id=${this.DISCORD_CLIENT_ID}`
            + `&redirect_uri=${window.location.origin}/auth`
            + '&response_type=code'
            + '&scope=identify guilds guilds.members.read';

I don't know if what you are using works but maybe something else now is broke.

Also now I changed from using docker to running front and back separately. And I see no errors from nothing now.

![Screenshot 2022-07-15 180345](https://user-images.githubusercontent.com/99339917/179262478-3f52b5ad-2a9e-457f-a91b-843c8540c11c.png)

**Comment by t-babin** [comment]
The ordering of those lines in that authorize function don't make a difference so that part is fine. The error interceptor is handling a non-401 error from the backend, which means there is some other form of error happening most likely in the API that is trying to authenticate with discord.

In this section of code it is logging any error response to both the dotnet console and to the log file, so you should be able to see what sort of error is happening if it is in fact related to the discord authentication

https://github.com/t-babin/ACC-Telemetry-Tracker/blob/aa24acc45d4095d79b0b05dcfaf7f0e196cbd8c6/server/AccTelemetryTracker.Api/Controllers/AuthController.cs#L54-L60

**Comment by AntVadala** [comment]
It says  {"error": "invalid_request", "error_description": "Invalid \"redirect_uri\" in request."}
[20:15:18 ERR] Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AccTelemetryTracker.Api.Controllers.AuthController.AuthCallback(String code) in /home/ubuntu/acc/server/AccTelemetryTracker.Api/Controllers/AuthController.cs:line 60
[20:15:18 INF] Request does not contain both the auth and user cookies

**Comment by AntVadala** [comment]
I found the problem and modified It a bit. By the way, can you send me all the tables and variables for the database?

**Comment by t-babin** [comment]
Glad you found the problem, feel free to open a PR with the changes and I can review and merge if necessary. The database schema is in `/datastore/init.sql`
